import { NextResponse } from 'next/server';

export const maxDuration = 60; // Allow up to 60 seconds for AI generation

export async function POST(req: Request) {
  try {
    const { messages } = await req.json();
    const apiKey = process.env.GROQ_API_KEY;

    if (!apiKey) {
      return NextResponse.json({ error: 'Server configuration error: Missing API Key' }, { status: 500 });
    }

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        messages,
        model: 'llama-3.3-70b-versatile'
      })
    });

    const data = await response.json();

    // Check for API errors (Rate limits, etc.)
    if (!response.ok) {
      console.error('Groq API Error:', data);
      
      let friendlyMessage = "Hình như mình đang bận một chút, bạn đợi xíu rồi nhắn lại nhé! 😅";
      
      if (response.status === 429) {
        friendlyMessage = "Nhiều bạn đang nhắn tin quá nên mình hơi quá tải, đợi mình vài giây rồi tâm sự tiếp nha! 😊";
      }

      // Return a fake AI response structure so the frontend doesn't crash
      return NextResponse.json({
        choices: [{
          message: {
            content: friendlyMessage
          }
        }]
      });
    }

    return NextResponse.json(data);
  } catch (error: any) {
    console.error('Chat API Error:', error);
    return NextResponse.json({
      choices: [{
        message: {
          content: "Oops! Có lỗi gì đó rồi, bạn kiểm tra lại kết nối hoặc nhắn lại sau nhé! 😅"
        }
      }]
    });
  }
}

// AUTOMATION: Generate Blog Idea via Cron Job
export async function GET(req: Request) {
  try {
    const authHeader = req.headers.get('authorization');
    const { searchParams } = new URL(req.url);
    const key = searchParams.get('key');
    
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && key !== process.env.CRON_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const apiKey = process.env.GROQ_API_KEY;
    const resendKey = process.env.RESEND_API_KEY;
    const receiverEmail = process.env.CONTACT_RECEIVER_EMAIL;
    const baseUrl = process.env.NEXTAUTH_URL;

    if (!baseUrl) {
      throw new Error("NEXTAUTH_URL is not defined in environment variables");
    }

    const prompt = `You are a creative technical content strategist. Generate a viral, catchy, and highly practical blog post title for a backend developer portfolio. 
    The topic should be modern (2026), slightly edgy, and combine backend expertise with real-world application (e.g., clever optimizations, new developer tools, AI integration, or career insights). 
    The topic MUST fall into one of these categories: [Technology, Backend, AI & ML, DevOps, System Design, Database, UI/UX, Career, Vibe Code, News].
    Avoid dry, academic System Design topics. Make it sound like a "must-read" article on Dev.to or Hacker News. 
    Output ONLY the title string, no quotes, no explanation.`;

    const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        messages: [{ role: "user", content: prompt }],
        model: 'llama-3.3-70b-versatile'
      })
    });

    const groqData = await groqRes.json();
    const idea = groqData.choices[0].message.content.trim();

    // Send Email via Resend
    const emailRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'AI Assistant <onboarding@resend.dev>',
        to: receiverEmail,
        subject: `✨ New Blog Idea: ${idea}`,
        html: `
          <div style="font-family: sans-serif; padding: 20px; color: #111;">
            <h2 style="color: #6366f1;">New AI-Powered Blog Idea</h2>
            <p>Hey Thach, I've got a fresh idea for your portfolio:</p>
            <div style="background: #f4f4f5; padding: 15px; border-left: 4px solid #6366f1; font-size: 18px; font-weight: bold; margin: 20px 0;">
              ${idea}
            </div>
            <p>If you like this, click the button below to generate full content and publish it automatically:</p>
            <a href="${baseUrl}/api/blog/automate?topic=${encodeURIComponent(idea)}" 
               style="background: #111; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-weight: bold; display: inline-block;">
              Publish Now ✨
            </a>
            <p style="font-size: 12px; color: #71717a; margin-top: 30px;">This idea was generated by Llama 3.3 via Groq.</p>
          </div>
        `
      })
    });

    return NextResponse.json({ success: true, idea });
  } catch (error: any) {
    console.error('Automation Error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
