import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from "@google/generative-ai";

export const maxDuration = 60; // Allow up to 60 seconds for AI generation

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_GENERATIVE_AI_API_KEY || "");

export async function POST(req: Request) {
  try {
    const { messages } = await req.json();
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // Convert message history for Gemini
    const chat = model.startChat({
      history: messages.slice(0, -1).map((msg: any) => ({
        role: msg.role === "user" ? "user" : "model",
        parts: [{ text: msg.content }],
      })),
    });

    const lastMessage = messages[messages.length - 1].content;
    const result = await chat.sendMessage(lastMessage);
    const response = await result.response;
    const text = response.text();

    return NextResponse.json({
      choices: [{
        message: {
          content: text
        }
      }]
    });
  } catch (error) {
    console.error("Gemini Chat Error:", error);
    return NextResponse.json({
      choices: [{
        message: {
          content: "Oops! Gemini đang bận một chút, bạn thử lại sau nhé! 😅"
        }
      }]
    });
  }
}

// AUTOMATION: Generate Blog Idea via Cron Job
export async function GET(req: Request) {
  try {
    const authHeader = req.headers.get('authorization');
    const { searchParams } = new URL(req.url);
    const key = searchParams.get('key');
    
    if (authHeader !== `Bearer ${process.env.CRON_SECRET}` && key !== process.env.CRON_SECRET) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const resendKey = process.env.RESEND_API_KEY;
    const receiverEmail = process.env.CONTACT_RECEIVER_EMAIL;
    const baseUrl = process.env.NEXTAUTH_URL;

    if (!baseUrl) {
      throw new Error("NEXTAUTH_URL is not defined in environment variables");
    }

    const prompt = `You are a relatable technical mentor. Generate a viral, catchy, and highly practical blog post title for a backend developer portfolio. 
    The topic should be at a Senior level or below, focusing on common pitfalls, subtle optimizations, or "underrated" best practices that developers often overlook in their day-to-day work. 
    Avoid overly complex architectural topics or high-level academic system design. Think about "hidden gems" or "things I wish I knew earlier" type of content.
    The topic MUST fall into one of these categories: [Technology, Backend, AI & ML, Algorithms, Programming Languages, System Design, Database, Career, Vibe Code, News].
    Output ONLY the title string, no quotes, no explanation.`;

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const idea = response.text().trim();

    if (!idea) {
      throw new Error("Failed to generate idea from Gemini");
    }

    // Send Email via Resend
    const emailRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'AI Assistant <onboarding@resend.dev>',
        to: receiverEmail,
        subject: `✨ New Blog Idea: ${idea}`,
        html: `
          <div style="font-family: sans-serif; padding: 20px; color: #111;">
            <h2 style="color: #6366f1;">New AI-Powered Blog Idea</h2>
            <p>I've brainstormed a new topic for your portfolio:</p>
            <div style="background: #f3f4f6; padding: 15px; border-radius: 10px; font-size: 1.2em; font-weight: bold; margin: 20px 0;">
              ${idea}
            </div>
            <p>Ready to turn this into a full article?</p>
            <a href="${baseUrl}/api/blog/automate?key=${process.env.CRON_SECRET}&idea=${encodeURIComponent(idea)}" 
               style="display: inline-block; background: #6366f1; color: white; padding: 12px 25px; border-radius: 8px; text-decoration: none; font-weight: bold;">
              🚀 Publish Now
            </a>
            <p style="color: #666; font-size: 0.8em; margin-top: 30px;">
              This idea was generated by Gemini 2.5 Flash based on your "Practical Mentor" persona.
            </p>
          </div>
        `
      })
    });

    return NextResponse.json({ success: true, idea });
  } catch (error: any) {
    console.error("Automation Error:", error);
    return NextResponse.json({ success: false, error: error.message });
  }
}
