import { NextResponse } from "next/server";
import { generateBlogContent } from "@/lib/gemini";
import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export const maxDuration = 60;

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const topic = searchParams.get("topic") || searchParams.get("idea");

    if (!topic) {
      return NextResponse.json({ error: "Missing topic" }, { status: 400 });
    }

    console.log(`🤖 Automating blog post for: ${topic}`);

    // 1. Call Gemini to generate full content
    const aiData = await generateBlogContent(topic);

    // 2. Save to MongoDB
    const post = await prisma.post.create({
      data: {
        ...aiData,
        slug: aiData.slug || aiData.title.en.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
        date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
        likes: Math.floor(Math.random() * 50) + 10,
      },
    });

    // 3. Revalidate paths
    revalidatePath("/blog");
    revalidatePath("/admin");

    // 4. Return success response with a nice UI message or redirect
    return new NextResponse(`
      <div style="font-family: sans-serif; text-align: center; padding: 50px;">
        <h1 style="color: #6366f1;">✅ Success!</h1>
        <p>The blog post "<strong>${post.title.en}</strong>" has been generated by AI and published.</p>
        <div style="margin: 30px 0;">
          <a href="/blog/${post.slug}" style="background: #111; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">View Post</a>
        </div>
        <p style="color: #71717a;">You can close this tab now.</p>
      </div>
    `, {
      headers: { "Content-Type": "text/html" },
    });

  } catch (error: any) {
    console.error("Automation Publish Error:", error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
